format = """
$hostname\
$directory\
$git_status\
$git_branch\
$line_break\
[>](bold 15) """

[directory]
truncation_length = 2
truncation_symbol = ""
style = "bold 250"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_branch]
truncation_length = 16
truncation_symbol = "…"
format = '[$branch](bold 244) '
